# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias emacs="emacs -nw"
  # delete all local branches
alias gdl="git branch | grep -v "master" | xargs git branch -D"

# Source bash autocompletion
if [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi