# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias te="emacs -nw"
alias saltall="sudo qubesctl --show-output --force-color --max-concurrency 4 --all state.highstate"
alias saltapps="sudo qubesctl --show-output --force-color --max-concurrency 4 --app state.highstate"
alias salttpl="sudo qubesctl --show-output --force-color --max-concurrency 4 --templates state.highstate"

saltone() {
    # run salt on one specific target
    sudo qubesctl --show-output --force-color --skip-dom0 --max-concurrency 1 --targets $1 state.highstate
    }

alias pi="ipython3 --no-confirm-exit"

# Source bash autocompletion
if [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi
