# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias emacs="emacs -nw"
alias saltall="sudo qubesctl --show-output --force-color --max-concurrency 1 --all state.highstate"
alias saltapps="sudo qubesctl --show-output --force-color --max-concurrency 1 --app state.highstate"
alias salttpl="sudo qubesctl --show-output --force-color --max-concurrency 1 --templates state.highstate"

# Source bash autocompletion
if [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi
