# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# set indent before starting tmux
  export ZLE_RPROMPT_INDENT=0

# Path to your oh-my-zsh installation.
  export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
  ZSH_THEME="powerlevel9k/powerlevel9k"
  POWERLEVEL9K_MODE='nerdfont-complete'
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi_mode root_indicator background_jobs history)

# START TMUX AUTOMATICALLY
  ZSH_TMUX_AUTOSTART='true'
  export TERM="st-256color"

# set indent after starting tmux
  export ZLE_RPROMPT_INDENT=0

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
  DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    tmux
    taskwarrior
    sudo
    history
    emacs
    zsh-autosuggestions
    zsh-syntax-highlighting
    vi-mode
)

source $ZSH/oh-my-zsh.sh

#################################################################
# User configuration
#################################################################

  ### Qubes Autocomplete (from Bash) ###
  if command -v qvm-ls --no-spinner > /dev/null 2>&1; then
      autoload -U bashcompinit
      bashcompinit
      source ~/.config/qvm-completion.bash
  fi

  ### MISC ###
  emacs-command-line () {
      local VISUAL="$EMACS_PLUGIN_LAUNCHER -t"
      local EDITOR="$EMACS_PLUGIN_LAUNCHER -t"
      TERM=xterm edit-command-line
  }
  zle -N emacs-command-line
  bindkey -M vicmd 'v' emacs-command-line
  bindkey -M vicmd 'e' emacs-command-line

  # Force user to type exit or logout to exit shell
  setopt ignoreeof

  ### EXPORTS ###
  export PATH=~/bin/:$PATH
  export VISUAL="$EMACS_PLUGIN_LAUNCHER -n"
  export EDITOR="TERM=xterm $EMACS_PLUGIN_LAUNCHER -t"
  export GIT_EDITOR=$EDITOR

  export KEYTIMEOUT=1

  # You may need to manually set your language environment
  export LANG=en_US.UTF-8

  ### ALIASES ###
  # alias zshconfig="mate ~/.zshrc"
  # alias ohmyzsh="mate ~/.oh-my-zsh"

  # delete all local branches
  alias gdl="git branch | grep -v "master" | xargs git branch -D"

  # ipython instead of python
  alias py=py3
  alias py2="ipython --no-confirm-exit"
  alias py3="ipython3 --no-confirm-exit"

  # editor aliases
  alias te="TERM=xterm $EMACS_PLUGIN_LAUNCHER -t"
  alias e="$EMACS_PLUGIN_LAUNCHER -n"
  alias ee="$EMACS_PLUGIN_LAUNCHER --alternate-editor '' -nc"

  # Salt Commands for Qubes
  if command -v qubesctl > /dev/null 2>&1; then
      alias saltall="sudo qubesctl --show-output \
             --force-color --max-concurrency 4 --all state.highstate"
      alias saltapps="sudo qubesctl --show-output \
        --force-color --max-concurrency 4 --app state.highstate"
      alias salttpl="sudo qubesctl --show-output \
        --force-color --max-concurrency 4 --templates state.highstate"
      alias saltdom="sudo qubesctl --show-output \
        --force-color --max-concurrency 1 --targets dom0 state.highstate"
      saltone() {
          # run salt on one specific target
          sudo qubesctl --max-concurrency 1 --show-output \
               --force-color --skip-dom0 --targets $1 state.highstate
      }
  fi

  # DONT REMOVE! #
  source /etc/profile

  # redefine ls aliases
  # (after /etc/profile because there is a script in profile.d overwriting my alias)
  alias ls="ls -F --color=auto"
  alias l="ls -lFh --color=auto"
  alias ll="ls -aFlh --color=auto"
